float64 ACyl_LC # arm cylinder pressure (large chamber)
float64 ACyl_SC # arm cylinder pressure (small chamber)
float64 Swing_L # swing pressure (left)
float64 Swing_R # swing pressure (right)

float64 BCyl_LC # boom cylinder pressure   (large chamber)
float64 BCyl_SC # boom cylinder pressure   (small chamber)
float64 KCyl_LC # bucket cylinder pressure (large chamber)
float64 KCyl_SC # bucket cylinder pressure (small chamber)
