# Request
Header header
sensor_msgs/Image img0 # boom upper camera (undistorted)
sensor_msgs/Image img1 # boom lower camera (undistorted)
float32 fx
float32 fy
float32 cx
float32 cy

float32 dist_k1
float32 dist_k2
float32 dist_p1
float32 dist_p2

---
# Response
Header header
bool success
geometry_msgs/Point[] tag_centers # 4개 3차원 점.